import { ref } from 'vue'

export const useNews = () => {


  const cards = ref([
    {
      slug: 'news-1',
      image: '/media/news2.png',
      date: '2024-06-29',
      descriptionKey: 'news.card1.description',
      source: 'news.card1.source',
      views: 320,
      contentDesc: '',
      files: [
        { url: '/pdfs/sample.pdf' },
        { url: '/pdfs/plan-2025.docx' },
      ],
    },
    {
      slug: 'news-2',
      image: '/media/news4.jpg',
      date: '2023-07-03',
      descriptionKey: 'news.card2.description',
      source: 'news.card2.source',
      views: 320,
      files: [
        { url: '/pdfs/sample.pdf' },
        { url: '/pdfs/plan-2025.docx' },
      ],
      letter: `
      <p>
        In accordance with the "Law of the People's Republic of China on Promoting Clean Production", "Measures for Clean Production Audits", and the "Notice on the Announcement of the List of Enterprises Subject to Mandatory Clean Production Audits in 2025" issued by the Development and Reform Commission of the Inner Mongolia Autonomous Region and the Department of Ecology and Environment of the Inner Mongolia Autonomous Region, Ordos Beiyuan Thermal Power Co., Ltd. launched the clean production audit in late April 2025 and established a clean production audit leading group to carry out various tasks.
      </p>
      <p>
        The company's environmental information is now disclosed to the public, and supervision and guidance from all sectors of society are welcome.
      </p>
      <ul>
        <li><strong>Company Name:</strong> Ordos Beiyuan Thermal Power Co., Ltd.</li>
        <li><strong>Legal Representative:</strong> Chen Yannan</li>
        <li><strong>Unit Address:</strong> In the yard of Mengtai Power Plant, No. 35, Yimei Road North, Dongsheng District, Ordos City</li>
        <li><strong>Main Products:</strong> electricity, heat</li>
        <li><strong>Hazardous Waste Treatment:</strong> The hazardous waste generated by Beiyuan Thermal Power Company during its operation is mainly waste mineral oil, waste catalysts, and waste lead-acid batteries. Beiyuan Thermal Power Company strictly stores them in the hazardous waste temporary storage of Mengtai Group in accordance with relevant national standards. In 2024, it entrusted Inner Mongolia Zhongxin Renewable Resources Technology Co., Ltd., which has relevant qualifications, to transfer and dispose of a total of 14.02 tons of waste mineral oil; it entrusted Ordos Menghong Renewable Resources Recycling Co., Ltd., which has relevant qualifications, to transfer and dispose of a total of 14.02 tons of waste mineral oil; it entrusted Gansu Yangguang Huishi Environmental Technology Co., Ltd., which has relevant qualifications, to transfer a total of 14.6 tons of waste vanadium-titanium catalysts. The above information has been reported in the Inner Mongolia Autonomous Region Solid Waste Management Information System and is publicized on the environmental information disclosure website in accordance with the law.</li>
      </ul>
      <p>
        Beiyuan Thermal Power Company mainly carries out its work in terms of saving energy resources, reducing pollutant emissions, and strengthening management. The content includes reducing the use of energy resources, reducing hazardous waste emissions, reducing leakage, strengthening the company's operational management, etc., so as to achieve the goals of saving energy resources and reducing pollutant emissions within the plant.
      </p>
      <p><strong>Publicity Period:</strong> May 10, 2025 - May 30, 2025</p>
      <p>Contact Number: 15804857776</p>
      <p>https://www.mengtaigroup.com/c/www/xwzx1/37653.jhtml</p>
      <h6>Ordos Beiyuan Thermal Power Co., Ltd.<br>May 7, 2025</h6>
    `
    },
    {
      slug: 'news-3',
      image: '/media/news7.jpg',
      date: '2022-04-05',
      descriptionKey: 'news.card3.description',
      source: 'news.card3.source',
      content: `
      <img src="/news7.jpg" alt="Environmental Impact Assessment Report" />
      <p>On June 29, Wang Lixia, Deputy Secretary of the Inner Mongolia Autonomous Region Party Committee and Chairman of the Autonomous Region People's Government, came to the Mengtai Dalate Aluminum Industrial Park to investigate the new technology and experimental progress of fly ash recycling. Gong Mingzhu, Director of the Autonomous Region Development and Reform Commission, Hu Ruifen, Deputy Director of the Autonomous Region Industry and Information Technology Department, and Jia Yubao, Secretary General of the Municipal Government, accompanied the investigation. Ao Fengting, Chairman of the Group, accompanied and introduced.</p>
      <p>In the group's fly ash preparation aluminum silicon alloy pilot workshop, Chairman Wang Lixia investigated the new fly ash recycling technology, learned about the progress of the experiment, and required the effective use of innovative achievements to accelerate the resource utilization of fly ash and other solid wastes to turn waste into treasure; encouraged enterprises to further extend the industrial chain and plan the aluminum post-processing industry chain using the refined aluminum silicon alloy raw materials.</p>
      
    `,
      views: 320,
      files: [
        { url: '/pdfs/sample.pdf' },
        { url: '/pdfs/plan-2025.docx' },
      ],
    },
    {
      slug: 'news-4',
      image: '/media/news-placeholder.png',
      date: '2024-06-12',
      descriptionKey: 'news.card4.description',
      source: 'news.card4.source',
      views: 1106,
      files: [
        { url: '/pdfs/sample.pdf' },
        { url: '/pdfs/plan-2025.docx' },
      ],
      content: `
      <img src="/contentDesc.jpg" alt="Mengtai Project Overview" />
      <p>Recently, Inner Mongolia Mengtai Group and Montana Group, the wholly-owned controlling shareholder of Alu Menziken (AME), a well-known European aluminum deep processing company, officially signed a contract to acquire 100% of AME's shares. After the acquisition is completed, Mengtai Group will become the wholly-owned controlling shareholder of AME Group. This is another important market M&A action of Mengtai after its acquisition of the European aluminum processing company, the German APT Group, in 2020.</p>
      <p> AME Group is a long-established manufacturer specializing in the production of aluminum lightweight parts, and enjoys a high reputation among customers for its consistently high quality products. The company currently has more than 700 employees, is headquartered in Reinach, Switzerland, and has 4 production bases in three European countries. AME has integrated production capabilities, covering the entire value chain including "raw material casting, extrusion, surface treatment and manufacturing component assembly". It mainly develops and produces electric battery system solutions, structural components and collision management systems, and provides products to key suppliers and original equipment manufacturers in the automotive manufacturing, construction, industry and pneumatic fields, including Porsche, Mercedes-Benz, BMW, Bosch, Hilti and other world-renowned brands</p>
      <img src="/contentDesc.jpg" alt="Mengtai Project Overview" />
      <p> Mr. Adams, CEO of AME, said: "AME's management team is very pleased to welcome an outstanding new shareholder. This is exciting news for our customers and suppliers. The joining of Mengtai will inject new impetus into AME's business development and innovative development."</p>
      <p> Mr. Ao Fengting, founder and chairman of Mengtai Group, said: "We will rely on AME's existing management team to continue to provide customers with high-quality products and services. In addition, AME and APT Aluminum's product lines are highly complementary, which will provide both parties with greater growth and innovation opportunities. In the future, Mengtai Group will continue to strengthen its strategic, R&D and marketWe will provide support and assistance in various aspects to ensure the continued growth of the Group’s European business.”</p>
      
    `,
      
    }
  ])

  const getNewsBySlug = (slug: string) => cards.value.find(card => card.slug === slug) || null

  return { cards, getNewsBySlug }
}
